[package]
name = "opensmtpd-filter-dkimout"
version = "0.1.0"
authors = ["Rodolphe Bréard <rodolphe@what.tf>"]
edition = "2021"
description = "DKIM filter for OpenSMTPD"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
env_logger = "^0.10"
log = "^0.4"
nom = "^7.1"
