Content-Type: multipart/alternative;
 boundary="part_eda940e4d8a6f09caf4178283d13aa8e07dff76459961d1a81551511a2ab9c82"; charset=UTF-8
Precedence: list
Message-Id: <e2b46b77-09ec-4df4-b305-e76484954ac3>
List-Archive: https://example.com/breard-r/opensmtpd-filter-dkimout
Date: Sun, 30 Apr 2023 07:59:36 -0700
List-Id: breard-r/opensmtpd-filter-dkimout
 <opensmtpd-filter-dkimout.breard-r.example.com>
List-Post: noreply@example.com
X-Example-Sender: breard-r
Reply-To: breard-r/opensmtpd-filter-dkimout
 <opensmtpd-filter-dkimout@noreply.example.com>
X-Example-Recipient: breard-r
X-Example-Reason: ci_activity
Subject: [breard-r/opensmtpd-filter-dkimout] Run cancelled: ci - main
 (8e75759)
Cc: "Ci activity" <ci_activity@noreply.example.com>
To: "breard-r/opensmtpd-filter-dkimout"
 <opensmtpd-filter-dkimout@noreply.example.com>
From: =?utf-8?q?Rodolphe_Br=C3=A9ard?= <notifications@example.com>
Mime-Version: 1.0

--part_eda940e4d8a6f09caf4178283d13aa8e07dff76459961d1a81551511a2ab9c82
Content-Transfer-Encoding: 7bit
Content-Type: text/plain; charset=UTF-8

[breard-r/opensmtpd-filter-dkimout] ci workflow run

Repository: breard-r/opensmtpd-filter-dkimout
Workflow: ci
Duration: 4 minutes and 16.0 seconds
Finished: 2023-04-30 14:59:25 UTC

View results: https://example.com/breard-r/opensmtpd-filter-dkimout/actions/runs/4844950945

Jobs:
  * Cargo fmt succeeded (0 annotations)
  * Integration test cancelled (8 annotations)
  * Cargo deny succeeded (0 annotations)
  * Cargo build & test (1.65.0) succeeded (9 annotations)
  * Cargo build & test (1.66.1) succeeded (9 annotations)
  * Cargo build & test (1.67.1) succeeded (9 annotations)
  * Cargo build & test (1.68.1) succeeded (9 annotations)
  * Cargo build & test (stable) succeeded (9 annotations)
  * Cargo build & test (beta) succeeded (9 annotations)
  * Cargo build & test (nightly) succeeded (9 annotations)
  * Black succeeded (0 annotations)

-- 
You are receiving this because you are subscribed to this thread.
Manage your Example Actions notifications: https://example.com/settings/notifications

--part_eda940e4d8a6f09caf4178283d13aa8e07dff76459961d1a81551511a2ab9c82
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset=UTF-8

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://ww=
w.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns=3D"http://www.w3.org/1999/xhtml" xmlns=3D"http://www.w3.org/1=
999/xhtml" lang=3D"en" xml:lang=3D"en" style=3D"font-family: sans-serif; =
-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; box-sizing: b=
order-box;" xml:lang=3D"en">
  <head>
    <meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dutf=
-8" />
    <meta name=3D"viewport" content=3D"width=3Ddevice-width" />
    <title>[breard-r/opensmtpd-filter-dkimout] Run cancelled: ci - main (=
8e75759)</title>
    =

  </head>
  <body style=3D"box-sizing: border-box; font-family: -apple-system,Blink=
MacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple=
 Color Emoji&quot;,&quot;Segoe UI Emoji&quot;; font-size: 14px; line-heig=
ht: 1.5; color: #24292e; background-color: #fff; margin: 0;" bgcolor=3D"#=
fff">
    <table align=3D"center" class=3D"container-sm width-full" width=3D"10=
0%" style=3D"box-sizing: border-box; border-spacing: 0; border-collapse: =
collapse; max-width: 544px; margin-right: auto; margin-left: auto; width:=
 100% !important; font-family: -apple-system,BlinkMacSystemFont,&quot;Seg=
oe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quo=
t;Segoe UI Emoji&quot; !important;">
      <tr style=3D"box-sizing: border-box; font-family: -apple-system,Bli=
nkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;App=
le Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
        <td class=3D"center p-3" align=3D"center" valign=3D"top" style=3D=
"box-sizing: border-box; font-family: -apple-system,BlinkMacSystemFont,&q=
uot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quo=
t;,&quot;Segoe UI Emoji&quot; !important; padding: 16px;">
          <center style=3D"box-sizing: border-box; font-family: -apple-sy=
stem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&=
quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
            <table border=3D"0" cellspacing=3D"0" cellpadding=3D"0" align=
=3D"center" class=3D"width-full container-md" width=3D"100%" style=3D"box=
-sizing: border-box; border-spacing: 0; border-collapse: collapse; max-wi=
dth: 768px; margin-right: auto; margin-left: auto; width: 100% !important=
; font-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helv=
etica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji=
&quot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td align=3D"center" style=3D"box-sizing: border-box; font-family: -a=
pple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-=
serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important=
; padding: 0;">
              <table style=3D"box-sizing: border-box; border-spacing: 0; =
border-collapse: collapse; font-family: -apple-system,BlinkMacSystemFont,=
&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&q=
uot;,&quot;Segoe UI Emoji&quot; !important;">
  <tbody style=3D"box-sizing: border-box; font-family: -apple-system,Blin=
kMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Appl=
e Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <tr style=3D"box-sizing: border-box; font-family: -apple-system,Blink=
MacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple=
 Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
      <td height=3D"16" style=3D"font-size: 16px; line-height: 16px; box-=
sizing: border-box; font-family: -apple-system,BlinkMacSystemFont,&quot;S=
egoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&q=
uot;Segoe UI Emoji&quot; !important; padding: 0;">&#160;</td>
    </tr>
  </tbody>
</table>

              <table border=3D"0" cellspacing=3D"0" cellpadding=3D"0" ali=
gn=3D"left" width=3D"100%" style=3D"box-sizing: border-box; border-spacin=
g: 0; border-collapse: collapse; font-family: -apple-system,BlinkMacSyste=
mFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color E=
moji&quot;,&quot;Segoe UI Emoji&quot; !important;">
                <tr style=3D"box-sizing: border-box; font-family: -apple-=
system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif=
,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
                  <td class=3D"text-left" style=3D"box-sizing: border-box=
; text-align: left !important; font-family: -apple-system,BlinkMacSystemF=
ont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emo=
ji&quot;,&quot;Segoe UI Emoji&quot; !important; padding: 0;" align=3D"lef=
t">
                    <img src=3D"https://assets.example.com/images/em=
ail/global/octocat-logo.png" alt=3D"Example" width=3D"32" style=3D"box-siz=
ing: border-box; font-family: -apple-system,BlinkMacSystemFont,&quot;Sego=
e UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot=
;Segoe UI Emoji&quot; !important; border-style: none;" />
                    <h2 class=3D"lh-condensed mt-2 text-normal" style=3D"=
box-sizing: border-box; margin-top: 8px !important; margin-bottom: 0; fon=
t-size: 24px; font-weight: 400 !important; line-height: 1.25 !important; =
font-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvet=
ica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&q=
uot; !important;">
                        [breard-r/opensmtpd-filter-dkimout] ci workflow r=
un

                    </h2>
                  </td>
                </tr>
              </table>
              <table style=3D"box-sizing: border-box; border-spacing: 0; =
border-collapse: collapse; font-family: -apple-system,BlinkMacSystemFont,=
&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&q=
uot;,&quot;Segoe UI Emoji&quot; !important;">
  <tbody style=3D"box-sizing: border-box; font-family: -apple-system,Blin=
kMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Appl=
e Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <tr style=3D"box-sizing: border-box; font-family: -apple-system,Blink=
MacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple=
 Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
      <td height=3D"16" style=3D"font-size: 16px; line-height: 16px; box-=
sizing: border-box; font-family: -apple-system,BlinkMacSystemFont,&quot;S=
egoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&q=
uot;Segoe UI Emoji&quot; !important; padding: 0;">&#160;</td>
    </tr>
  </tbody>
</table>

</td>
  </tr>
</table>
            <table width=3D"100%" class=3D"width-full" style=3D"box-sizin=
g: border-box; border-spacing: 0; border-collapse: collapse; width: 100% =
!important; font-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&=
quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Sego=
e UI Emoji&quot; !important;">
              <tr style=3D"box-sizing: border-box; font-family: -apple-sy=
stem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&=
quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
                <td class=3D"border rounded-2 d-block" style=3D"box-sizin=
g: border-box; border-radius: 6px !important; display: block !important; =
font-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvet=
ica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&q=
uot; !important; padding: 0; border: 1px solid #e1e4e8;">
                  <table align=3D"center" class=3D"width-full text-center=
" style=3D"box-sizing: border-box; border-spacing: 0; border-collapse: co=
llapse; width: 100% !important; text-align: center !important; font-famil=
y: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,=
sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !impo=
rtant;">
                    <tr style=3D"box-sizing: border-box; font-family: -ap=
ple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-s=
erif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;=
">
                      <td style=3D"box-sizing: border-box; font-family: -=
apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans=
-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !importan=
t; padding: 0;">
                        <table border=3D"0" cellspacing=3D"0" cellpadding=
=3D"0" align=3D"center" class=3D"width-full" width=3D"100%" style=3D"box-=
sizing: border-box; border-spacing: 0; border-collapse: collapse; width: =
100% !important; font-family: -apple-system,BlinkMacSystemFont,&quot;Sego=
e UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot=
;Segoe UI Emoji&quot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td align=3D"center" style=3D"box-sizing: border-box; font-family: -a=
pple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-=
serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important=
; padding: 0;">
                          =

<table align=3D"center" class=3D"border-bottom width-full text-center" st=
yle=3D"box-sizing: border-box; border-spacing: 0; border-collapse: collap=
se; border-bottom-width: 1px !important; border-bottom-color: #e1e4e8 !im=
portant; border-bottom-style: solid !important; width: 100% !important; t=
ext-align: center !important; font-family: -apple-system,BlinkMacSystemFo=
nt,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoj=
i&quot;,&quot;Segoe UI Emoji&quot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td class=3D"d-block px-3 pt-3 p-sm-4" style=3D"box-sizing: border-bo=
x; display: block !important; font-family: -apple-system,BlinkMacSystemFo=
nt,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoj=
i&quot;,&quot;Segoe UI Emoji&quot; !important; padding: 24px;">
      <table border=3D"0" cellspacing=3D"0" cellpadding=3D"0" align=3D"ce=
nter" class=3D"width-full" width=3D"100%" style=3D"box-sizing: border-box=
; border-spacing: 0; border-collapse: collapse; width: 100% !important; f=
ont-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helveti=
ca,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&qu=
ot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td align=3D"center" style=3D"box-sizing: border-box; font-family: -a=
pple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-=
serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important=
; padding: 0;">
        =

    <img src=3D"https://assets.example.com/images/email/icons/action=
s.png" width=3D"56" height=3D"56" alt=3D"" style=3D"box-sizing: border-bo=
x; font-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Hel=
vetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoj=
i&quot; !important; border-style: none;" />
  <table style=3D"box-sizing: border-box; border-spacing: 0; border-colla=
pse: collapse; font-family: -apple-system,BlinkMacSystemFont,&quot;Segoe =
UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;S=
egoe UI Emoji&quot; !important;">
  <tbody style=3D"box-sizing: border-box; font-family: -apple-system,Blin=
kMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Appl=
e Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <tr style=3D"box-sizing: border-box; font-family: -apple-system,Blink=
MacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple=
 Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
      <td height=3D"12" style=3D"font-size: 12px; line-height: 12px; box-=
sizing: border-box; font-family: -apple-system,BlinkMacSystemFont,&quot;S=
egoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&q=
uot;Segoe UI Emoji&quot; !important; padding: 0;">&#160;</td>
    </tr>
  </tbody>
</table>

<h3 class=3D"lh-condensed" style=3D"box-sizing: border-box; margin-top: 0=
; margin-bottom: 0; font-size: 20px; font-weight: 600; line-height: 1.25 =
!important; font-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&=
quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Sego=
e UI Emoji&quot; !important;">ci: Some jobs were not successful</h3>
<table style=3D"box-sizing: border-box; border-spacing: 0; border-collaps=
e: collapse; font-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI=
&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Seg=
oe UI Emoji&quot; !important;">
  <tbody style=3D"box-sizing: border-box; font-family: -apple-system,Blin=
kMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Appl=
e Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <tr style=3D"box-sizing: border-box; font-family: -apple-system,Blink=
MacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple=
 Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
      <td height=3D"16" style=3D"font-size: 16px; line-height: 16px; box-=
sizing: border-box; font-family: -apple-system,BlinkMacSystemFont,&quot;S=
egoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&q=
uot;Segoe UI Emoji&quot; !important; padding: 0;">&#160;</td>
    </tr>
  </tbody>
</table>



  <table border=3D"0" cellspacing=3D"0" cellpadding=3D"0" align=3D"center=
" class=3D"width-full" width=3D"100%" style=3D"box-sizing: border-box; bo=
rder-spacing: 0; border-collapse: collapse; width: 100% !important; font-=
family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,A=
rial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; =
!important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td align=3D"center" style=3D"box-sizing: border-box; font-family: -a=
pple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-=
serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important=
; padding: 0;">
    <table width=3D"100%" border=3D"0" cellspacing=3D"0" cellpadding=3D"0=
" style=3D"box-sizing: border-box; border-spacing: 0; border-collapse: co=
llapse; font-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot=
;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI=
 Emoji&quot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td style=3D"box-sizing: border-box; font-family: -apple-system,Blink=
MacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple=
 Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; padding: 0;">
      <table border=3D"0" cellspacing=3D"0" cellpadding=3D"0" width=3D"10=
0%" style=3D"box-sizing: border-box; border-spacing: 0; border-collapse: =
collapse; font-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&qu=
ot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe =
UI Emoji&quot; !important;">
        <tr style=3D"box-sizing: border-box; font-family: -apple-system,B=
linkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;A=
pple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
          <td align=3D"center" style=3D"box-sizing: border-box; font-fami=
ly: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial=
,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !imp=
ortant; padding: 0;">
              <!--[if mso]> <table><tr><td align=3D"center" bgcolor=3D"#2=
8a745"> <![endif]-->
                <a href=3D"https://example.com/breard-r/opensmtpd-filter-d=
kimout/actions/runs/4844950945" target=3D"_blank" class=3D"btn btn-large =
btn-primary" style=3D"background-color: #28a745 !important; box-sizing: b=
order-box; color: #fff; text-decoration: none; position: relative; displa=
y: inline-block; font-size: inherit; font-weight: 500; line-height: 1.5; =
white-space: nowrap; vertical-align: middle; cursor: pointer; -webkit-use=
r-select: none; user-select: none; border-radius: .5em; -webkit-appearanc=
e: none; appearance: none; box-shadow: 0 1px 0 rgba(27,31,35,.1),inset 0 =
1px 0 rgba(255,255,255,.03); transition: background-color .2s cubic-bezie=
r(0.3, 0, 0.5, 1); font-family: -apple-system,BlinkMacSystemFont,&quot;Se=
goe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&qu=
ot;Segoe UI Emoji&quot; !important; padding: .75em 1.5em; border: 1px sol=
id #28a745;">View workflow run</a>
              <!--[if mso]> </td></tr></table> <![endif]-->
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>

</td>
  </tr>
</table>
  <table style=3D"box-sizing: border-box; border-spacing: 0; border-colla=
pse: collapse; font-family: -apple-system,BlinkMacSystemFont,&quot;Segoe =
UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;S=
egoe UI Emoji&quot; !important;">
  <tbody style=3D"box-sizing: border-box; font-family: -apple-system,Blin=
kMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Appl=
e Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <tr style=3D"box-sizing: border-box; font-family: -apple-system,Blink=
MacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple=
 Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
      <td height=3D"32" style=3D"font-size: 32px; line-height: 32px; box-=
sizing: border-box; font-family: -apple-system,BlinkMacSystemFont,&quot;S=
egoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&q=
uot;Segoe UI Emoji&quot; !important; padding: 0;">&#160;</td>
    </tr>
  </tbody>
</table>


</td>
  </tr>
</table>
    </td>
  </tr>
</table>

  <table align=3D"center" class=3D"border-bottom width-full text-center" =
style=3D"box-sizing: border-box; border-spacing: 0; border-collapse: coll=
apse; border-bottom-width: 1px !important; border-bottom-color: #e1e4e8 !=
important; border-bottom-style: solid !important; width: 100% !important;=
 text-align: center !important; font-family: -apple-system,BlinkMacSystem=
Font,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Em=
oji&quot;,&quot;Segoe UI Emoji&quot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td class=3D"d-block text-left" style=3D"box-sizing: border-box; text=
-align: left !important; display: block !important; font-family: -apple-s=
ystem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,=
&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; padd=
ing: 0;" align=3D"left">
      <table border=3D"0" cellspacing=3D"0" cellpadding=3D"0" align=3D"ce=
nter" class=3D"width-full" width=3D"100%" style=3D"box-sizing: border-box=
; border-spacing: 0; border-collapse: collapse; width: 100% !important; f=
ont-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helveti=
ca,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&qu=
ot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td align=3D"center" style=3D"box-sizing: border-box; font-family: -a=
pple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-=
serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important=
; padding: 0;">
        =

    </td><td class=3D"pl-3 py-3 p-sm-4" style=3D"box-sizing: border-box; =
font-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvet=
ica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&q=
uot; !important; padding: 24px;">
      <img src=3D"https://assets.example.com/images/email/icons/chec=
k-circle-fill-green.png" alt=3D"Cargo fmt" height=3D"24" width=3D"24" sty=
le=3D"box-sizing: border-box; font-family: -apple-system,BlinkMacSystemFo=
nt,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoj=
i&quot;,&quot;Segoe UI Emoji&quot; !important; border-style: none;" />
    </td>
    <td style=3D"width: 100%; box-sizing: border-box; font-family: -apple=
-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-seri=
f,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; pa=
dding: 16px;" class=3D"p-3">
      <p class=3D"mb-0" style=3D"box-sizing: border-box; margin-top: 0; m=
argin-bottom: 0 !important; font-family: -apple-system,BlinkMacSystemFont=
,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&=
quot;,&quot;Segoe UI Emoji&quot; !important;">
        <b style=3D"font-weight: 600; box-sizing: border-box; font-family=
: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,s=
ans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !impor=
tant;">ci</b> / Cargo fmt
        <br style=3D"box-sizing: border-box; font-family: -apple-system,B=
linkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;A=
pple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;" />
        Succeeded in 6 seconds
      </p>
    </td>
    <td style=3D"white-space: nowrap; box-sizing: border-box; font-family=
: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,s=
ans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !impor=
tant; padding: 16px 16px 16px 0;" class=3D"pr-3 py-3">
    </td>


  </tr>
</table>
    </td>
  </tr>
</table>
  <table align=3D"center" class=3D"border-bottom width-full text-center" =
style=3D"box-sizing: border-box; border-spacing: 0; border-collapse: coll=
apse; border-bottom-width: 1px !important; border-bottom-color: #e1e4e8 !=
important; border-bottom-style: solid !important; width: 100% !important;=
 text-align: center !important; font-family: -apple-system,BlinkMacSystem=
Font,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Em=
oji&quot;,&quot;Segoe UI Emoji&quot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td class=3D"d-block text-left" style=3D"box-sizing: border-box; text=
-align: left !important; display: block !important; font-family: -apple-s=
ystem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,=
&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; padd=
ing: 0;" align=3D"left">
      <table border=3D"0" cellspacing=3D"0" cellpadding=3D"0" align=3D"ce=
nter" class=3D"width-full" width=3D"100%" style=3D"box-sizing: border-box=
; border-spacing: 0; border-collapse: collapse; width: 100% !important; f=
ont-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helveti=
ca,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&qu=
ot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td align=3D"center" style=3D"box-sizing: border-box; font-family: -a=
pple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-=
serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important=
; padding: 0;">
        =

    </td><td class=3D"pl-3 py-3 p-sm-4" style=3D"box-sizing: border-box; =
font-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvet=
ica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&q=
uot; !important; padding: 24px;">
      <img src=3D"https://assets.example.com/images/email/icons/x-ci=
rcle-fill-red.png" alt=3D"Integration test" height=3D"24" width=3D"24" st=
yle=3D"box-sizing: border-box; font-family: -apple-system,BlinkMacSystemF=
ont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emo=
ji&quot;,&quot;Segoe UI Emoji&quot; !important; border-style: none;" />
    </td>
    <td style=3D"width: 100%; box-sizing: border-box; font-family: -apple=
-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-seri=
f,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; pa=
dding: 16px;" class=3D"p-3">
      <p class=3D"mb-0" style=3D"box-sizing: border-box; margin-top: 0; m=
argin-bottom: 0 !important; font-family: -apple-system,BlinkMacSystemFont=
,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&=
quot;,&quot;Segoe UI Emoji&quot; !important;">
        <b style=3D"font-weight: 600; box-sizing: border-box; font-family=
: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,s=
ans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !impor=
tant;">ci</b> / Integration test
        <br style=3D"box-sizing: border-box; font-family: -apple-system,B=
linkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;A=
pple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;" />
        Cancelled
      </p>
    </td>
    <td style=3D"white-space: nowrap; box-sizing: border-box; font-family=
: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,s=
ans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !impor=
tant; padding: 16px 16px 16px 0;" class=3D"pr-3 py-3">
        <a href=3D"https://example.com/breard-r/opensmtpd-filter-dkimout/a=
ctions/runs/4844950945" style=3D"background-color: transparent; box-sizin=
g: border-box; color: #0366d6; text-decoration: none; font-family: -apple=
-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-seri=
f,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
          <img src=3D"https://assets.example.com/images/email/icons/=
report-gray.png" alt=3D"annotations for ci / Integration test" width=3D"1=
6" height=3D"16" style=3D"box-sizing: border-box; font-family: -apple-sys=
tem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&q=
uot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; border=
-style: none;" />
          <span class=3D"d-table-cell v-align-middle text-gray-light" sty=
le=3D"box-sizing: border-box; color: #6a737d !important; vertical-align: =
middle !important; display: table-cell !important; font-family: -apple-sy=
stem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&=
quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;"> 8 <=
/span>
        </a>
    </td>


  </tr>
</table>
    </td>
  </tr>
</table>
  <table align=3D"center" class=3D"border-bottom width-full text-center" =
style=3D"box-sizing: border-box; border-spacing: 0; border-collapse: coll=
apse; border-bottom-width: 1px !important; border-bottom-color: #e1e4e8 !=
important; border-bottom-style: solid !important; width: 100% !important;=
 text-align: center !important; font-family: -apple-system,BlinkMacSystem=
Font,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Em=
oji&quot;,&quot;Segoe UI Emoji&quot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td class=3D"d-block text-left" style=3D"box-sizing: border-box; text=
-align: left !important; display: block !important; font-family: -apple-s=
ystem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,=
&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; padd=
ing: 0;" align=3D"left">
      <table border=3D"0" cellspacing=3D"0" cellpadding=3D"0" align=3D"ce=
nter" class=3D"width-full" width=3D"100%" style=3D"box-sizing: border-box=
; border-spacing: 0; border-collapse: collapse; width: 100% !important; f=
ont-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helveti=
ca,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&qu=
ot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td align=3D"center" style=3D"box-sizing: border-box; font-family: -a=
pple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-=
serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important=
; padding: 0;">
        =

    </td><td class=3D"pl-3 py-3 p-sm-4" style=3D"box-sizing: border-box; =
font-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvet=
ica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&q=
uot; !important; padding: 24px;">
      <img src=3D"https://assets.example.com/images/email/icons/chec=
k-circle-fill-green.png" alt=3D"Cargo deny" height=3D"24" width=3D"24" st=
yle=3D"box-sizing: border-box; font-family: -apple-system,BlinkMacSystemF=
ont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emo=
ji&quot;,&quot;Segoe UI Emoji&quot; !important; border-style: none;" />
    </td>
    <td style=3D"width: 100%; box-sizing: border-box; font-family: -apple=
-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-seri=
f,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; pa=
dding: 16px;" class=3D"p-3">
      <p class=3D"mb-0" style=3D"box-sizing: border-box; margin-top: 0; m=
argin-bottom: 0 !important; font-family: -apple-system,BlinkMacSystemFont=
,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&=
quot;,&quot;Segoe UI Emoji&quot; !important;">
        <b style=3D"font-weight: 600; box-sizing: border-box; font-family=
: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,s=
ans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !impor=
tant;">ci</b> / Cargo deny
        <br style=3D"box-sizing: border-box; font-family: -apple-system,B=
linkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;A=
pple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;" />
        Succeeded in 1 minute and 47 seconds
      </p>
    </td>
    <td style=3D"white-space: nowrap; box-sizing: border-box; font-family=
: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,s=
ans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !impor=
tant; padding: 16px 16px 16px 0;" class=3D"pr-3 py-3">
    </td>


  </tr>
</table>
    </td>
  </tr>
</table>
  <table align=3D"center" class=3D"border-bottom width-full text-center" =
style=3D"box-sizing: border-box; border-spacing: 0; border-collapse: coll=
apse; border-bottom-width: 1px !important; border-bottom-color: #e1e4e8 !=
important; border-bottom-style: solid !important; width: 100% !important;=
 text-align: center !important; font-family: -apple-system,BlinkMacSystem=
Font,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Em=
oji&quot;,&quot;Segoe UI Emoji&quot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td class=3D"d-block text-left" style=3D"box-sizing: border-box; text=
-align: left !important; display: block !important; font-family: -apple-s=
ystem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,=
&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; padd=
ing: 0;" align=3D"left">
      <table border=3D"0" cellspacing=3D"0" cellpadding=3D"0" align=3D"ce=
nter" class=3D"width-full" width=3D"100%" style=3D"box-sizing: border-box=
; border-spacing: 0; border-collapse: collapse; width: 100% !important; f=
ont-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helveti=
ca,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&qu=
ot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td align=3D"center" style=3D"box-sizing: border-box; font-family: -a=
pple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-=
serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important=
; padding: 0;">
        =

    </td><td class=3D"pl-3 py-3 p-sm-4" style=3D"box-sizing: border-box; =
font-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvet=
ica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&q=
uot; !important; padding: 24px;">
      <img src=3D"https://assets.example.com/images/email/icons/chec=
k-circle-fill-green.png" alt=3D"Cargo build &amp; test (1.65.0)" height=3D=
"24" width=3D"24" style=3D"box-sizing: border-box; font-family: -apple-sy=
stem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&=
quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; borde=
r-style: none;" />
    </td>
    <td style=3D"width: 100%; box-sizing: border-box; font-family: -apple=
-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-seri=
f,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; pa=
dding: 16px;" class=3D"p-3">
      <p class=3D"mb-0" style=3D"box-sizing: border-box; margin-top: 0; m=
argin-bottom: 0 !important; font-family: -apple-system,BlinkMacSystemFont=
,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&=
quot;,&quot;Segoe UI Emoji&quot; !important;">
        <b style=3D"font-weight: 600; box-sizing: border-box; font-family=
: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,s=
ans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !impor=
tant;">ci</b> / Cargo build &amp; test (1.65.0)
        <br style=3D"box-sizing: border-box; font-family: -apple-system,B=
linkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;A=
pple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;" />
        Succeeded in 2 minutes and 30 seconds
      </p>
    </td>
    <td style=3D"white-space: nowrap; box-sizing: border-box; font-family=
: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,s=
ans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !impor=
tant; padding: 16px 16px 16px 0;" class=3D"pr-3 py-3">
        <a href=3D"https://example.com/breard-r/opensmtpd-filter-dkimout/a=
ctions/runs/4844950945" style=3D"background-color: transparent; box-sizin=
g: border-box; color: #0366d6; text-decoration: none; font-family: -apple=
-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-seri=
f,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
          <img src=3D"https://assets.example.com/images/email/icons/=
report-gray.png" alt=3D"annotations for ci / Cargo build &amp; test (1.65=
.0)" width=3D"16" height=3D"16" style=3D"box-sizing: border-box; font-fam=
ily: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Aria=
l,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !im=
portant; border-style: none;" />
          <span class=3D"d-table-cell v-align-middle text-gray-light" sty=
le=3D"box-sizing: border-box; color: #6a737d !important; vertical-align: =
middle !important; display: table-cell !important; font-family: -apple-sy=
stem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&=
quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;"> 9 <=
/span>
        </a>
    </td>


  </tr>
</table>
    </td>
  </tr>
</table>
  <table align=3D"center" class=3D"border-bottom width-full text-center" =
style=3D"box-sizing: border-box; border-spacing: 0; border-collapse: coll=
apse; border-bottom-width: 1px !important; border-bottom-color: #e1e4e8 !=
important; border-bottom-style: solid !important; width: 100% !important;=
 text-align: center !important; font-family: -apple-system,BlinkMacSystem=
Font,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Em=
oji&quot;,&quot;Segoe UI Emoji&quot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td class=3D"d-block text-left" style=3D"box-sizing: border-box; text=
-align: left !important; display: block !important; font-family: -apple-s=
ystem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,=
&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; padd=
ing: 0;" align=3D"left">
      <table border=3D"0" cellspacing=3D"0" cellpadding=3D"0" align=3D"ce=
nter" class=3D"width-full" width=3D"100%" style=3D"box-sizing: border-box=
; border-spacing: 0; border-collapse: collapse; width: 100% !important; f=
ont-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helveti=
ca,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&qu=
ot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td align=3D"center" style=3D"box-sizing: border-box; font-family: -a=
pple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-=
serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important=
; padding: 0;">
        =

    </td><td class=3D"pl-3 py-3 p-sm-4" style=3D"box-sizing: border-box; =
font-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvet=
ica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&q=
uot; !important; padding: 24px;">
      <img src=3D"https://assets.example.com/images/email/icons/chec=
k-circle-fill-green.png" alt=3D"Cargo build &amp; test (1.66.1)" height=3D=
"24" width=3D"24" style=3D"box-sizing: border-box; font-family: -apple-sy=
stem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&=
quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; borde=
r-style: none;" />
    </td>
    <td style=3D"width: 100%; box-sizing: border-box; font-family: -apple=
-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-seri=
f,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; pa=
dding: 16px;" class=3D"p-3">
      <p class=3D"mb-0" style=3D"box-sizing: border-box; margin-top: 0; m=
argin-bottom: 0 !important; font-family: -apple-system,BlinkMacSystemFont=
,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&=
quot;,&quot;Segoe UI Emoji&quot; !important;">
        <b style=3D"font-weight: 600; box-sizing: border-box; font-family=
: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,s=
ans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !impor=
tant;">ci</b> / Cargo build &amp; test (1.66.1)
        <br style=3D"box-sizing: border-box; font-family: -apple-system,B=
linkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;A=
pple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;" />
        Succeeded in 2 minutes and 28 seconds
      </p>
    </td>
    <td style=3D"white-space: nowrap; box-sizing: border-box; font-family=
: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,s=
ans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !impor=
tant; padding: 16px 16px 16px 0;" class=3D"pr-3 py-3">
        <a href=3D"https://example.com/breard-r/opensmtpd-filter-dkimout/a=
ctions/runs/4844950945" style=3D"background-color: transparent; box-sizin=
g: border-box; color: #0366d6; text-decoration: none; font-family: -apple=
-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-seri=
f,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
          <img src=3D"https://assets.example.com/images/email/icons/=
report-gray.png" alt=3D"annotations for ci / Cargo build &amp; test (1.66=
.1)" width=3D"16" height=3D"16" style=3D"box-sizing: border-box; font-fam=
ily: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Aria=
l,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !im=
portant; border-style: none;" />
          <span class=3D"d-table-cell v-align-middle text-gray-light" sty=
le=3D"box-sizing: border-box; color: #6a737d !important; vertical-align: =
middle !important; display: table-cell !important; font-family: -apple-sy=
stem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&=
quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;"> 9 <=
/span>
        </a>
    </td>


  </tr>
</table>
    </td>
  </tr>
</table>
  <table align=3D"center" class=3D"border-bottom width-full text-center" =
style=3D"box-sizing: border-box; border-spacing: 0; border-collapse: coll=
apse; border-bottom-width: 1px !important; border-bottom-color: #e1e4e8 !=
important; border-bottom-style: solid !important; width: 100% !important;=
 text-align: center !important; font-family: -apple-system,BlinkMacSystem=
Font,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Em=
oji&quot;,&quot;Segoe UI Emoji&quot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td class=3D"d-block text-left" style=3D"box-sizing: border-box; text=
-align: left !important; display: block !important; font-family: -apple-s=
ystem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,=
&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; padd=
ing: 0;" align=3D"left">
      <table border=3D"0" cellspacing=3D"0" cellpadding=3D"0" align=3D"ce=
nter" class=3D"width-full" width=3D"100%" style=3D"box-sizing: border-box=
; border-spacing: 0; border-collapse: collapse; width: 100% !important; f=
ont-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helveti=
ca,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&qu=
ot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td align=3D"center" style=3D"box-sizing: border-box; font-family: -a=
pple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-=
serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important=
; padding: 0;">
        =

    </td><td class=3D"pl-3 py-3 p-sm-4" style=3D"box-sizing: border-box; =
font-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvet=
ica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&q=
uot; !important; padding: 24px;">
      <img src=3D"https://assets.example.com/images/email/icons/chec=
k-circle-fill-green.png" alt=3D"Cargo build &amp; test (1.67.1)" height=3D=
"24" width=3D"24" style=3D"box-sizing: border-box; font-family: -apple-sy=
stem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&=
quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; borde=
r-style: none;" />
    </td>
    <td style=3D"width: 100%; box-sizing: border-box; font-family: -apple=
-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-seri=
f,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; pa=
dding: 16px;" class=3D"p-3">
      <p class=3D"mb-0" style=3D"box-sizing: border-box; margin-top: 0; m=
argin-bottom: 0 !important; font-family: -apple-system,BlinkMacSystemFont=
,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&=
quot;,&quot;Segoe UI Emoji&quot; !important;">
        <b style=3D"font-weight: 600; box-sizing: border-box; font-family=
: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,s=
ans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !impor=
tant;">ci</b> / Cargo build &amp; test (1.67.1)
        <br style=3D"box-sizing: border-box; font-family: -apple-system,B=
linkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;A=
pple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;" />
        Succeeded in 2 minutes and 41 seconds
      </p>
    </td>
    <td style=3D"white-space: nowrap; box-sizing: border-box; font-family=
: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,s=
ans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !impor=
tant; padding: 16px 16px 16px 0;" class=3D"pr-3 py-3">
        <a href=3D"https://example.com/breard-r/opensmtpd-filter-dkimout/a=
ctions/runs/4844950945" style=3D"background-color: transparent; box-sizin=
g: border-box; color: #0366d6; text-decoration: none; font-family: -apple=
-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-seri=
f,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
          <img src=3D"https://assets.example.com/images/email/icons/=
report-gray.png" alt=3D"annotations for ci / Cargo build &amp; test (1.67=
.1)" width=3D"16" height=3D"16" style=3D"box-sizing: border-box; font-fam=
ily: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Aria=
l,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !im=
portant; border-style: none;" />
          <span class=3D"d-table-cell v-align-middle text-gray-light" sty=
le=3D"box-sizing: border-box; color: #6a737d !important; vertical-align: =
middle !important; display: table-cell !important; font-family: -apple-sy=
stem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&=
quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;"> 9 <=
/span>
        </a>
    </td>


  </tr>
</table>
    </td>
  </tr>
</table>
  <table align=3D"center" class=3D"border-bottom width-full text-center" =
style=3D"box-sizing: border-box; border-spacing: 0; border-collapse: coll=
apse; border-bottom-width: 1px !important; border-bottom-color: #e1e4e8 !=
important; border-bottom-style: solid !important; width: 100% !important;=
 text-align: center !important; font-family: -apple-system,BlinkMacSystem=
Font,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Em=
oji&quot;,&quot;Segoe UI Emoji&quot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td class=3D"d-block text-left" style=3D"box-sizing: border-box; text=
-align: left !important; display: block !important; font-family: -apple-s=
ystem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,=
&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; padd=
ing: 0;" align=3D"left">
      <table border=3D"0" cellspacing=3D"0" cellpadding=3D"0" align=3D"ce=
nter" class=3D"width-full" width=3D"100%" style=3D"box-sizing: border-box=
; border-spacing: 0; border-collapse: collapse; width: 100% !important; f=
ont-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helveti=
ca,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&qu=
ot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td align=3D"center" style=3D"box-sizing: border-box; font-family: -a=
pple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-=
serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important=
; padding: 0;">
        =

    </td><td class=3D"pl-3 py-3 p-sm-4" style=3D"box-sizing: border-box; =
font-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvet=
ica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&q=
uot; !important; padding: 24px;">
      <img src=3D"https://assets.example.com/images/email/icons/chec=
k-circle-fill-green.png" alt=3D"Cargo build &amp; test (1.68.1)" height=3D=
"24" width=3D"24" style=3D"box-sizing: border-box; font-family: -apple-sy=
stem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&=
quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; borde=
r-style: none;" />
    </td>
    <td style=3D"width: 100%; box-sizing: border-box; font-family: -apple=
-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-seri=
f,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; pa=
dding: 16px;" class=3D"p-3">
      <p class=3D"mb-0" style=3D"box-sizing: border-box; margin-top: 0; m=
argin-bottom: 0 !important; font-family: -apple-system,BlinkMacSystemFont=
,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&=
quot;,&quot;Segoe UI Emoji&quot; !important;">
        <b style=3D"font-weight: 600; box-sizing: border-box; font-family=
: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,s=
ans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !impor=
tant;">ci</b> / Cargo build &amp; test (1.68.1)
        <br style=3D"box-sizing: border-box; font-family: -apple-system,B=
linkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;A=
pple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;" />
        Succeeded in 2 minutes and 27 seconds
      </p>
    </td>
    <td style=3D"white-space: nowrap; box-sizing: border-box; font-family=
: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,s=
ans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !impor=
tant; padding: 16px 16px 16px 0;" class=3D"pr-3 py-3">
        <a href=3D"https://example.com/breard-r/opensmtpd-filter-dkimout/a=
ctions/runs/4844950945" style=3D"background-color: transparent; box-sizin=
g: border-box; color: #0366d6; text-decoration: none; font-family: -apple=
-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-seri=
f,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
          <img src=3D"https://assets.example.com/images/email/icons/=
report-gray.png" alt=3D"annotations for ci / Cargo build &amp; test (1.68=
.1)" width=3D"16" height=3D"16" style=3D"box-sizing: border-box; font-fam=
ily: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Aria=
l,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !im=
portant; border-style: none;" />
          <span class=3D"d-table-cell v-align-middle text-gray-light" sty=
le=3D"box-sizing: border-box; color: #6a737d !important; vertical-align: =
middle !important; display: table-cell !important; font-family: -apple-sy=
stem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&=
quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;"> 9 <=
/span>
        </a>
    </td>


  </tr>
</table>
    </td>
  </tr>
</table>
  <table align=3D"center" class=3D"border-bottom width-full text-center" =
style=3D"box-sizing: border-box; border-spacing: 0; border-collapse: coll=
apse; border-bottom-width: 1px !important; border-bottom-color: #e1e4e8 !=
important; border-bottom-style: solid !important; width: 100% !important;=
 text-align: center !important; font-family: -apple-system,BlinkMacSystem=
Font,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Em=
oji&quot;,&quot;Segoe UI Emoji&quot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td class=3D"d-block text-left" style=3D"box-sizing: border-box; text=
-align: left !important; display: block !important; font-family: -apple-s=
ystem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,=
&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; padd=
ing: 0;" align=3D"left">
      <table border=3D"0" cellspacing=3D"0" cellpadding=3D"0" align=3D"ce=
nter" class=3D"width-full" width=3D"100%" style=3D"box-sizing: border-box=
; border-spacing: 0; border-collapse: collapse; width: 100% !important; f=
ont-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helveti=
ca,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&qu=
ot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td align=3D"center" style=3D"box-sizing: border-box; font-family: -a=
pple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-=
serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important=
; padding: 0;">
        =

    </td><td class=3D"pl-3 py-3 p-sm-4" style=3D"box-sizing: border-box; =
font-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvet=
ica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&q=
uot; !important; padding: 24px;">
      <img src=3D"https://assets.example.com/images/email/icons/chec=
k-circle-fill-green.png" alt=3D"Cargo build &amp; test (stable)" height=3D=
"24" width=3D"24" style=3D"box-sizing: border-box; font-family: -apple-sy=
stem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&=
quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; borde=
r-style: none;" />
    </td>
    <td style=3D"width: 100%; box-sizing: border-box; font-family: -apple=
-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-seri=
f,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; pa=
dding: 16px;" class=3D"p-3">
      <p class=3D"mb-0" style=3D"box-sizing: border-box; margin-top: 0; m=
argin-bottom: 0 !important; font-family: -apple-system,BlinkMacSystemFont=
,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&=
quot;,&quot;Segoe UI Emoji&quot; !important;">
        <b style=3D"font-weight: 600; box-sizing: border-box; font-family=
: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,s=
ans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !impor=
tant;">ci</b> / Cargo build &amp; test (stable)
        <br style=3D"box-sizing: border-box; font-family: -apple-system,B=
linkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;A=
pple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;" />
        Succeeded in 2 minutes and 45 seconds
      </p>
    </td>
    <td style=3D"white-space: nowrap; box-sizing: border-box; font-family=
: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,s=
ans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !impor=
tant; padding: 16px 16px 16px 0;" class=3D"pr-3 py-3">
        <a href=3D"https://example.com/breard-r/opensmtpd-filter-dkimout/a=
ctions/runs/4844950945" style=3D"background-color: transparent; box-sizin=
g: border-box; color: #0366d6; text-decoration: none; font-family: -apple=
-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-seri=
f,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
          <img src=3D"https://assets.example.com/images/email/icons/=
report-gray.png" alt=3D"annotations for ci / Cargo build &amp; test (stab=
le)" width=3D"16" height=3D"16" style=3D"box-sizing: border-box; font-fam=
ily: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Aria=
l,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !im=
portant; border-style: none;" />
          <span class=3D"d-table-cell v-align-middle text-gray-light" sty=
le=3D"box-sizing: border-box; color: #6a737d !important; vertical-align: =
middle !important; display: table-cell !important; font-family: -apple-sy=
stem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&=
quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;"> 9 <=
/span>
        </a>
    </td>


  </tr>
</table>
    </td>
  </tr>
</table>
  <table align=3D"center" class=3D"border-bottom width-full text-center" =
style=3D"box-sizing: border-box; border-spacing: 0; border-collapse: coll=
apse; border-bottom-width: 1px !important; border-bottom-color: #e1e4e8 !=
important; border-bottom-style: solid !important; width: 100% !important;=
 text-align: center !important; font-family: -apple-system,BlinkMacSystem=
Font,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Em=
oji&quot;,&quot;Segoe UI Emoji&quot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td class=3D"d-block text-left" style=3D"box-sizing: border-box; text=
-align: left !important; display: block !important; font-family: -apple-s=
ystem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,=
&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; padd=
ing: 0;" align=3D"left">
      <table border=3D"0" cellspacing=3D"0" cellpadding=3D"0" align=3D"ce=
nter" class=3D"width-full" width=3D"100%" style=3D"box-sizing: border-box=
; border-spacing: 0; border-collapse: collapse; width: 100% !important; f=
ont-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helveti=
ca,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&qu=
ot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td align=3D"center" style=3D"box-sizing: border-box; font-family: -a=
pple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-=
serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important=
; padding: 0;">
        =

    </td><td class=3D"pl-3 py-3 p-sm-4" style=3D"box-sizing: border-box; =
font-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvet=
ica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&q=
uot; !important; padding: 24px;">
      <img src=3D"https://assets.example.com/images/email/icons/chec=
k-circle-fill-green.png" alt=3D"Cargo build &amp; test (beta)" height=3D"=
24" width=3D"24" style=3D"box-sizing: border-box; font-family: -apple-sys=
tem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&q=
uot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; border=
-style: none;" />
    </td>
    <td style=3D"width: 100%; box-sizing: border-box; font-family: -apple=
-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-seri=
f,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; pa=
dding: 16px;" class=3D"p-3">
      <p class=3D"mb-0" style=3D"box-sizing: border-box; margin-top: 0; m=
argin-bottom: 0 !important; font-family: -apple-system,BlinkMacSystemFont=
,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&=
quot;,&quot;Segoe UI Emoji&quot; !important;">
        <b style=3D"font-weight: 600; box-sizing: border-box; font-family=
: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,s=
ans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !impor=
tant;">ci</b> / Cargo build &amp; test (beta)
        <br style=3D"box-sizing: border-box; font-family: -apple-system,B=
linkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;A=
pple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;" />
        Succeeded in 1 minute and 53 seconds
      </p>
    </td>
    <td style=3D"white-space: nowrap; box-sizing: border-box; font-family=
: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,s=
ans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !impor=
tant; padding: 16px 16px 16px 0;" class=3D"pr-3 py-3">
        <a href=3D"https://example.com/breard-r/opensmtpd-filter-dkimout/a=
ctions/runs/4844950945" style=3D"background-color: transparent; box-sizin=
g: border-box; color: #0366d6; text-decoration: none; font-family: -apple=
-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-seri=
f,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
          <img src=3D"https://assets.example.com/images/email/icons/=
report-gray.png" alt=3D"annotations for ci / Cargo build &amp; test (beta=
)" width=3D"16" height=3D"16" style=3D"box-sizing: border-box; font-famil=
y: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,=
sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !impo=
rtant; border-style: none;" />
          <span class=3D"d-table-cell v-align-middle text-gray-light" sty=
le=3D"box-sizing: border-box; color: #6a737d !important; vertical-align: =
middle !important; display: table-cell !important; font-family: -apple-sy=
stem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&=
quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;"> 9 <=
/span>
        </a>
    </td>


  </tr>
</table>
    </td>
  </tr>
</table>
  <table align=3D"center" class=3D"border-bottom width-full text-center" =
style=3D"box-sizing: border-box; border-spacing: 0; border-collapse: coll=
apse; border-bottom-width: 1px !important; border-bottom-color: #e1e4e8 !=
important; border-bottom-style: solid !important; width: 100% !important;=
 text-align: center !important; font-family: -apple-system,BlinkMacSystem=
Font,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Em=
oji&quot;,&quot;Segoe UI Emoji&quot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td class=3D"d-block text-left" style=3D"box-sizing: border-box; text=
-align: left !important; display: block !important; font-family: -apple-s=
ystem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,=
&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; padd=
ing: 0;" align=3D"left">
      <table border=3D"0" cellspacing=3D"0" cellpadding=3D"0" align=3D"ce=
nter" class=3D"width-full" width=3D"100%" style=3D"box-sizing: border-box=
; border-spacing: 0; border-collapse: collapse; width: 100% !important; f=
ont-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helveti=
ca,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&qu=
ot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td align=3D"center" style=3D"box-sizing: border-box; font-family: -a=
pple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-=
serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important=
; padding: 0;">
        =

    </td><td class=3D"pl-3 py-3 p-sm-4" style=3D"box-sizing: border-box; =
font-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvet=
ica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&q=
uot; !important; padding: 24px;">
      <img src=3D"https://assets.example.com/images/email/icons/chec=
k-circle-fill-green.png" alt=3D"Cargo build &amp; test (nightly)" height=3D=
"24" width=3D"24" style=3D"box-sizing: border-box; font-family: -apple-sy=
stem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&=
quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; borde=
r-style: none;" />
    </td>
    <td style=3D"width: 100%; box-sizing: border-box; font-family: -apple=
-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-seri=
f,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important; pa=
dding: 16px;" class=3D"p-3">
      <p class=3D"mb-0" style=3D"box-sizing: border-box; margin-top: 0; m=
argin-bottom: 0 !important; font-family: -apple-system,BlinkMacSystemFont=
,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&=
quot;,&quot;Segoe UI Emoji&quot; !important;">
        <b style=3D"font-weight: 600; box-sizing: border-box; font-family=
: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,s=
ans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !impor=
tant;">ci</b> / Cargo build &amp; test (nightly)
        <br style=3D"box-sizing: border-box; font-family: -apple-system,B=
linkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;A=
pple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;" />
        Succeeded in 1 minute and 28 seconds
      </p>
    </td>
    <td style=3D"white-space: nowrap; box-sizing: border-box; font-family=
: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,s=
ans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !impor=
tant; padding: 16px 16px 16px 0;" class=3D"pr-3 py-3">
        <a href=3D"https://example.com/breard-r/opensmtpd-filter-dkimout/a=
ctions/runs/4844950945" style=3D"background-color: transparent; box-sizin=
g: border-box; color: #0366d6; text-decoration: none; font-family: -apple=
-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-seri=
f,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
          <img src=3D"https://assets.example.com/images/email/icons/=
report-gray.png" alt=3D"annotations for ci / Cargo build &amp; test (nigh=
tly)" width=3D"16" height=3D"16" style=3D"box-sizing: border-box; font-fa=
mily: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Ari=
al,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !i=
mportant; border-style: none;" />
          <span class=3D"d-table-cell v-align-middle text-gray-light" sty=
le=3D"box-sizing: border-box; color: #6a737d !important; vertical-align: =
middle !important; display: table-cell !important; font-family: -apple-sy=
stem,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&=
quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;"> 9 <=
/span>
        </a>
    </td>


  </tr>
</table>
    </td>
  </tr>
</table>

  <table align=3D"center" class=3D"width-full text-center" style=3D"box-s=
izing: border-box; border-spacing: 0; border-collapse: collapse; width: 1=
00% !important; text-align: center !important; font-family: -apple-system=
,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot=
;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td class=3D"d-block px-3 pt-3 p-sm-4" style=3D"box-sizing: border-bo=
x; display: block !important; font-family: -apple-system,BlinkMacSystemFo=
nt,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoj=
i&quot;,&quot;Segoe UI Emoji&quot; !important; padding: 24px;">
      <table border=3D"0" cellspacing=3D"0" cellpadding=3D"0" align=3D"ce=
nter" class=3D"width-full" width=3D"100%" style=3D"box-sizing: border-box=
; border-spacing: 0; border-collapse: collapse; width: 100% !important; f=
ont-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helveti=
ca,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&qu=
ot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td align=3D"center" style=3D"box-sizing: border-box; font-family: -a=
pple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-=
serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important=
; padding: 0;">
        =

    <table class=3D"width-full" style=3D"box-sizing: border-box; border-s=
pacing: 0; border-collapse: collapse; width: 100% !important; font-family=
: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,s=
ans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !impor=
tant;">
  <tbody style=3D"box-sizing: border-box; font-family: -apple-system,Blin=
kMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Appl=
e Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <tr class=3D"v-align-middle" style=3D"box-sizing: border-box; vertica=
l-align: middle !important; font-family: -apple-system,BlinkMacSystemFont=
,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&=
quot;,&quot;Segoe UI Emoji&quot; !important;">
      =

      <a href=3D"https://example.com/breard-r/opensmtpd-filter-dkimout/act=
ions/runs/4844950945" class=3D"text-emphasized color-fg-accent" style=3D"=
background-color: transparent; box-sizing: border-box; color: #24292e; te=
xt-decoration: none; font-weight: 600; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
        View all 11 job statuses
      </a>

    </tr>
  </tbody>
</table>

</td>
  </tr>
</table>
    </td>
  </tr>
</table>
  <table style=3D"box-sizing: border-box; border-spacing: 0; border-colla=
pse: collapse; font-family: -apple-system,BlinkMacSystemFont,&quot;Segoe =
UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;S=
egoe UI Emoji&quot; !important;">
  <tbody style=3D"box-sizing: border-box; font-family: -apple-system,Blin=
kMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Appl=
e Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <tr style=3D"box-sizing: border-box; font-family: -apple-system,Blink=
MacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple=
 Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
      <td height=3D"16" style=3D"font-size: 16px; line-height: 16px; box-=
sizing: border-box; font-family: -apple-system,BlinkMacSystemFont,&quot;S=
egoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&q=
uot;Segoe UI Emoji&quot; !important; padding: 0;">&#160;</td>
    </tr>
  </tbody>
</table>



</td>
  </tr>
</table>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>
            <table border=3D"0" cellspacing=3D"0" cellpadding=3D"0" align=
=3D"center" class=3D"width-full text-center" width=3D"100%" style=3D"box-=
sizing: border-box; border-spacing: 0; border-collapse: collapse; width: =
100% !important; text-align: center !important; font-family: -apple-syste=
m,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quo=
t;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td align=3D"center" style=3D"box-sizing: border-box; font-family: -a=
pple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-=
serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important=
; padding: 0;">
              <table style=3D"box-sizing: border-box; border-spacing: 0; =
border-collapse: collapse; font-family: -apple-system,BlinkMacSystemFont,=
&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&q=
uot;,&quot;Segoe UI Emoji&quot; !important;">
  <tbody style=3D"box-sizing: border-box; font-family: -apple-system,Blin=
kMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Appl=
e Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <tr style=3D"box-sizing: border-box; font-family: -apple-system,Blink=
MacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple=
 Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
      <td height=3D"16" style=3D"font-size: 16px; line-height: 16px; box-=
sizing: border-box; font-family: -apple-system,BlinkMacSystemFont,&quot;S=
egoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&q=
uot;Segoe UI Emoji&quot; !important; padding: 0;">&#160;</td>
    </tr>
  </tbody>
</table>

              <table style=3D"box-sizing: border-box; border-spacing: 0; =
border-collapse: collapse; font-family: -apple-system,BlinkMacSystemFont,=
&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&q=
uot;,&quot;Segoe UI Emoji&quot; !important;">
  <tbody style=3D"box-sizing: border-box; font-family: -apple-system,Blin=
kMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Appl=
e Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <tr style=3D"box-sizing: border-box; font-family: -apple-system,Blink=
MacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple=
 Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
      <td height=3D"16" style=3D"font-size: 16px; line-height: 16px; box-=
sizing: border-box; font-family: -apple-system,BlinkMacSystemFont,&quot;S=
egoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&q=
uot;Segoe UI Emoji&quot; !important; padding: 0;">&#160;</td>
    </tr>
  </tbody>
</table>

              <p class=3D"f5 text-gray-light" style=3D"box-sizing: border=
-box; margin-top: 0; margin-bottom: 10px; color: #6a737d !important; font=
-size: 14px !important; font-family: -apple-system,BlinkMacSystemFont,&qu=
ot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot=
;,&quot;Segoe UI Emoji&quot; !important;">  </p><p style=3D"font-size: sm=
all; -webkit-text-size-adjust: none; color: #666; box-sizing: border-box;=
 margin-top: 0; margin-bottom: 10px; font-family: -apple-system,BlinkMacS=
ystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Col=
or Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">&#8212;<br style=3D=
"box-sizing: border-box; font-family: -apple-system,BlinkMacSystemFont,&q=
uot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quo=
t;,&quot;Segoe UI Emoji&quot; !important;" />You are receiving this becau=
se you are subscribed to this thread.<br style=3D"box-sizing: border-box;=
 font-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helve=
tica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&=
quot; !important;" /><a href=3D"https://example.com/settings/notifications=
" style=3D"background-color: transparent; box-sizing: border-box; color: =
#0366d6; text-decoration: none; font-family: -apple-system,BlinkMacSystem=
Font,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Em=
oji&quot;,&quot;Segoe UI Emoji&quot; !important;">Manage your Example Acti=
ons notifications</a></p>

</td>
  </tr>
</table>
            <table border=3D"0" cellspacing=3D"0" cellpadding=3D"0" align=
=3D"center" class=3D"width-full text-center" width=3D"100%" style=3D"box-=
sizing: border-box; border-spacing: 0; border-collapse: collapse; width: =
100% !important; text-align: center !important; font-family: -apple-syste=
m,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quo=
t;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
  <tr style=3D"box-sizing: border-box; font-family: -apple-system,BlinkMa=
cSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple C=
olor Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <td align=3D"center" style=3D"box-sizing: border-box; font-family: -a=
pple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-=
serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important=
; padding: 0;">
  <table style=3D"box-sizing: border-box; border-spacing: 0; border-colla=
pse: collapse; font-family: -apple-system,BlinkMacSystemFont,&quot;Segoe =
UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;S=
egoe UI Emoji&quot; !important;">
  <tbody style=3D"box-sizing: border-box; font-family: -apple-system,Blin=
kMacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Appl=
e Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
    <tr style=3D"box-sizing: border-box; font-family: -apple-system,Blink=
MacSystemFont,&quot;Segoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple=
 Color Emoji&quot;,&quot;Segoe UI Emoji&quot; !important;">
      <td height=3D"16" style=3D"font-size: 16px; line-height: 16px; box-=
sizing: border-box; font-family: -apple-system,BlinkMacSystemFont,&quot;S=
egoe UI&quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&q=
uot;Segoe UI Emoji&quot; !important; padding: 0;">&#160;</td>
    </tr>
  </tbody>
</table>

  <p class=3D"f6 text-gray-light" style=3D"box-sizing: border-box; margin=
-top: 0; margin-bottom: 10px; color: #6a737d !important; font-size: 12px =
!important; font-family: -apple-system,BlinkMacSystemFont,&quot;Segoe UI&=
quot;,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Sego=
e UI Emoji&quot; !important;">Example, Inc. &#12539;88 Colin P Kelly Jr St=
reet &#12539;San Francisco, CA 94107</p>
</td>
  </tr>
</table>

          </center>
        </td>
      </tr>
    </table>
    <!-- prevent Gmail on iOS font size manipulation -->
   <div style=3D"display: none; white-space: nowrap; box-sizing: border-b=
ox; font: 15px/0 apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;,H=
elvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Em=
oji&quot;;"> &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#16=
0; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; =
&#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#1=
60; </div>
  </body>
</html>

--part_eda940e4d8a6f09caf4178283d13aa8e07dff76459961d1a81551511a2ab9c82--
